version: "3"
services:
  book-portal-db:
    image: mysql:8.0
    container_name: "book-portal-db"
    restart: always
    environment:
      MYSQL_DATABASE: book_portal
      MYSQL_ROOT_PASSWORD: bookportal123

  book-portal-be:
    build: ./book-portal-be
    container_name: "book-portal-be"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://book-portal-db:3306/book_portal?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: bookportal123
    depends_on:
      - book-portal-db

  book-portal-fe:
    build: ./book-portal-fe
    container_name: "book-portal-fe"
    depends_on:
      - book-portal-be

  proxy:
    build: ./nginx
    container_name: "book-portal-proxy"
    restart: always
    ports:
      - "80:80"